language: android
sudo: false ## Enable container-based infrastructure
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
    - chmod +x gradlew
    - chmod +x scripts/do.sh
script:
    - ./scripts/do.sh
