language: android
sudo: false ## Enable container-based infrastructure
android:
  components:
    - android-23
    - tools
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
    - chmod +x gradlew
    - chmod +x scripts/do.sh
script:
    - ./scripts/do.sh
